server:
  port: 8001
mybatis:
  type-aliases-package: com.tan.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=ture&characterEncoding=utf-8
    username: root
    password: qq8804902

#eureka的配置ka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/


#info配置

